# Config file for automatic testing at travis-ci.org

language: python

install: pip install tox

script:
  - tox

env:
  - TOXENV=py27-dj17
  - TOXENV=py33-dj17
  - TOXENV=py34-dj17
  - TOXENV=flake8
  - TOXENV=coverage
